import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { AlertTriangle, Inbox, RefreshCw } from 'lucide-react';
import { cn } from '@/lib/cn';
import { Button } from '@/components/ui/Button';
export const Skeleton = ({ className }) => (_jsx("div", { className: cn('animate-pulse rounded-md bg-slate-200 dark:bg-slate-800', className) }));
/** Squelette de tableau : evite le saut de mise en page au chargement. */
export const TableSkeleton = ({ rows = 6, columns = 4 }) => (_jsx("div", { className: "divide-y divide-slate-100 dark:divide-slate-800", children: Array.from({ length: rows }).map((_, rowIndex) => (_jsx("div", { className: "flex items-center gap-4 px-4 py-3", children: Array.from({ length: columns }).map((__, columnIndex) => (_jsx(Skeleton, { className: cn('h-4', columnIndex === 0 ? 'w-1/4' : 'flex-1', columnIndex === columns - 1 && 'w-16 flex-none') }, columnIndex))) }, rowIndex))) }));
export const EmptyState = ({ title, description, icon, action, }) => (_jsxs("div", { className: "flex flex-col items-center justify-center gap-3 px-6 py-14 text-center", children: [_jsx("span", { className: "flex h-11 w-11 items-center justify-center rounded-full bg-slate-100 text-slate-400 dark:bg-slate-800 dark:text-slate-500", children: icon ?? _jsx(Inbox, { className: "h-5 w-5" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-slate-800 dark:text-slate-200", children: title }), description ? _jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: description }) : null] }), action] }));
export const ErrorState = ({ message, onRetry, }) => (_jsxs("div", { className: "flex flex-col items-center justify-center gap-3 px-6 py-14 text-center", children: [_jsx("span", { className: "flex h-11 w-11 items-center justify-center rounded-full bg-rose-50 text-rose-500 dark:bg-rose-500/10 dark:text-rose-400", children: _jsx(AlertTriangle, { className: "h-5 w-5" }) }), _jsxs("div", { children: [_jsx("p", { className: "text-sm font-semibold text-slate-800 dark:text-slate-200", children: "Chargement impossible" }), _jsx("p", { className: "mt-1 text-xs text-slate-500 dark:text-slate-400", children: message ?? 'Une erreur est survenue.' })] }), onRetry ? (_jsx(Button, { variant: "secondary", size: "sm", icon: _jsx(RefreshCw, { className: "h-3.5 w-3.5" }), onClick: onRetry, children: "R\u00E9essayer" })) : null] }));
/** État vide compact pour les listes imbriquées. */
export const InlineEmpty = ({ children }) => (_jsx("p", { className: "px-4 py-6 text-center text-xs text-slate-500 dark:text-slate-400", children: children }));
