import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { cn } from '@/lib/cn';
const CONTROL_BASE = 'block w-full rounded-lg border-0 bg-white px-3 py-2 text-sm text-slate-900 shadow-sm ring-1 ring-inset ring-slate-300 placeholder:text-slate-400 focus:ring-2 focus:ring-inset focus:ring-brand-600 disabled:bg-slate-50 disabled:text-slate-500 dark:bg-slate-900 dark:text-slate-100 dark:ring-slate-600 dark:placeholder:text-slate-500 dark:focus:ring-brand-500 dark:disabled:bg-slate-800/50';
export const Field = ({ label, hint, error, required, children, className }) => (_jsxs("div", { className: cn('space-y-1.5', className), children: [label ? (_jsxs("label", { className: "block text-xs font-medium text-slate-700 dark:text-slate-300", children: [label, required ? _jsx("span", { className: "ml-0.5 text-rose-500", children: "*" }) : null] })) : null, children, error ? (_jsx("p", { className: "text-xs font-medium text-rose-600 dark:text-rose-400", children: error })) : hint ? (_jsx("p", { className: "text-xs text-slate-500 dark:text-slate-400", children: hint })) : null] }));
export const Input = ({ className, ...props }) => (_jsx("input", { className: cn(CONTROL_BASE, className), ...props }));
export const Textarea = ({ className, rows = 3, ...props }) => (_jsx("textarea", { rows: rows, className: cn(CONTROL_BASE, 'resize-y', className), ...props }));
export const Select = ({ className, children, ...props }) => (_jsx("select", { className: cn(CONTROL_BASE, 'pr-8', className), ...props, children: children }));
/** Case a cocher avec libelle inline. */
export const Checkbox = ({ label, hint, className, ...props }) => (_jsxs("label", { className: cn('flex items-start gap-2.5', className), children: [_jsx("input", { type: "checkbox", className: "mt-0.5 h-4 w-4 rounded border-slate-300 text-brand-600 focus:ring-brand-600 dark:border-slate-600 dark:bg-slate-800", ...props }), _jsxs("span", { className: "text-sm text-slate-700 dark:text-slate-300", children: [label, hint ? _jsx("span", { className: "block text-xs text-slate-500 dark:text-slate-400", children: hint }) : null] })] }));
